@ECHO off
date /T>"%~dp0temp\date.var"&& time /T>"%~dp0temp\time.var"
SET /P date=<"%~dp0temp\date.var" && SET /P time=<"%~dp0temp\time.var"
SET /P username=<"%~dp0config\user.ini"
echo ^<mark name="START"/^> >>"%~dp0temp\startup.voice"
echo ^<speak^> >>"%~dp0temp\startup.voice"
echo ^<p^> >>"%~dp0temp\startup.voice"
echo ^<s^> >>"%~dp0temp\startup.voice"
echo Hello %username%, welcome to ^<say-as interpret-as="characters"^> Keukeiland ^</say-as^> . >>"%~dp0temp\startup.voice"
echo ^</s^> >>"%~dp0temp\startup.voice"
echo ^</speak^> >>"%~dp0temp\startup.voice"
echo ^</mark name="END"/^> >>"%~dp0temp\startup.voice"
call "%~dp0soundengine.bat" "%~dp0temp\startup.voice"
erase /F "%~dp0temp\startup.voice"
